### ISSUE TITLE
Leetcode Question Number 565

### ISSUE THREAD

**Issue by uzair-ali10** [amanv8060/Leetcode-Questions#442]
Leetcode Question Number 565 soultion needs to be added in the repo . 
 The link for the question is [this](https://leetcode.com/problems/array-nesting).
 Accepted Languages C++ / JAVA . 
 You Only need to add the  class Solution in the file. 
 Make Sure you have read the contributions guidelines before creating an PR.

**Comment by Anusrita02** [comment]
Assign
